### PR TITLE
[BUGFIX] Corrected check to automatically polyfill older browsers

### PR DESCRIPTION
**Pull request by haassie**
The code will now correctly check if the animate functions are available in the browser. If not, it will automatically polyfill.

Resolves: #1

### CODE REVIEW

**Comment by notoriousb1t** [comment]
Thanks for the contribution 😄

**Comment by haassie** [comment]
Thanks @notoriousb1t ! Is it possible to create a release and to publish it?

**Comment by georgringer** [comment]
@haassie 0.4.1 has been released

**Comment by haassie** [comment]
I know. Thanks a lot @notoriousb1t !

**Pull request merged**
